import { Card, Checkbox, List, Typography } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import data from "../utils/groceryList.json";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grocery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography.Title>Grocery</Typography.Title>
        <List
          grid={{
            gutter: 16,
            column: 1,
          }}
          dataSource={data}
          renderItem={(item) => (
            <List.Item>
              <Card title={item.title}>
                {item.contents?.map((content, index) => (
                  <Checkbox key={index}>{content}</Checkbox>
                ))}
              </Card>
            </List.Item>
          )}
        />
      </main>
    </div>
  );
};

export default Home;
